# The Revival of Alternative Music: A Response to the Exhaustion of Commercial Music?

## Project Overview

In recent years, alternative music has experienced renewed interest among listeners. This phenomenon has sparked discussions about whether this resurgence represents a reaction to the standardization of commercial music or a search for more authentic and emotionally complex artistic expressions.
The purpose of this project is to analyze the emotional and sonic characteristics of alternative music tracks in order to identify patterns that distinguish them from the dominant trends found in contemporary commercial music.
Through the analysis of musical variables obtained from APIs and other music-related data sources, this study explores whether factors such as emotional tone, intensity, acoustic production, and danceability reflect a growing preference for music perceived as more human, imperfect, and emotionally authentic.


## Research Question

**Do contemporary alternative music tracks exhibit emotional and sonic characteristics that differentiate them from dominant commercial music?**


## Variables Analyzed

| Variable | Description | Type |
|-----------|-------------|-------------|
| `valence` | Perceived emotional positivity or negativity of a track. | float64
| `energy` | Level of intensity and activity. |float64
| `acousticness` | Degree of acoustic production. |float64
| `danceability` | Suitability of a track for dancing. |float64
| `release_year` | Release date information. |datetime
| `name` | Track name. |string
| `artists` | Artist name. |string
| `id` | Unique track identifier. |string
| `group` | Category to which the track belongs (Alternative or Commercial). |string

## Objectives

- Compare the emotional characteristics of alternative and commercial music.
- Analyze differences in acoustic production and energy levels.
- Identify patterns associated with alternative music.
- Explore whether alternative music reflects a shift toward more emotionally complex and authentic artistic expressions.

## Expected Outcome

This project aims to identify whether alternative music demonstrates distinct emotional and sonic patterns when compared to commercial music, potentially reflecting changing listener preferences and broader cultural trends.

In [65]:
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from riffscope.features import read_csv,merge_df

In [66]:
alternative_df,comercial_df = read_csv()
df_merge = merge_df(alternative_df,comercial_df)
df_merge.info()
df_merge.head()

<class 'pandas.DataFrame'>
RangeIndex: 1785 entries, 0 to 1784
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1785 non-null   str
 1   name          1785 non-null   str
 2   artists       1785 non-null   str
 3   release_date  1785 non-null   str
 4   acousticness  1785 non-null   float64
 5   danceability  1785 non-null   float64
 6   energy        1785 non-null   float64
 7   valence       1785 non-null   float64
 8   group         1785 non-null   str
dtypes: float64(4), str(5)
memory usage: 125.6 KB

,id,name,artists,release_date,acousticness,danceability,energy,valence,group
0,0COqiPhxzoWICwFCS4eZcp,Bring Me To Life,Evanescence,2003-03-04,0.00721,0.331,0.943,0.296,alternative
1,70LcF31zb1H0PyJoS1Sx1r,Creep,Radiohead,1993-02-22,0.00970,0.515,0.430,0.104,alternative
2,6Qyc6fS4DsZjB2mRW9DsQs,Iris,The Goo Goo Dolls,1998,0.00125,0.315,0.715,0.497,alternative
3,003vvx7Niy0yvhvHt4a68B,Mr. Brightside,The Killers,2004,0.00121,0.352,0.911,0.236,alternative
4,5UWwZ5lm5PKu6eKsHAGxOk,Everlong,Foo Fighters,1997-05-20,0.00006,0.413,0.881,0.364,alternative

In [67]:
df_merge.describe()

       acousticness  danceability       energy      valence
count   1785.000000   1785.000000  1785.000000  1785.000000
mean       0.196196      0.566573     0.705218     0.522039
std        0.254210      0.172505     0.204895     0.245565
min        0.000002      0.000000     0.025700     0.000000
25%        0.005990      0.454000     0.573000     0.336000
50%        0.064400      0.580000     0.748000     0.521000
75%        0.319000      0.699000     0.871000     0.724000
max        0.987000      0.967000     0.997000     0.985000

In [68]:
df_merge.isnull().sum()

id              0
name            0
artists         0
release_date    0
acousticness    0
danceability    0
energy          0
valence         0
group           0
dtype: int64

In [69]:
#Subniveles 
col_cat = ['group','artists','id','name']

for col in col_cat:
    print(f"{col}:{df_merge[col].nunique()} subniveles")

group:2 subniveles
artists:957 subniveles
id:1745 subniveles
name:1679 subniveles

Duplicados

In [71]:

dups = df_merge[df_merge.duplicated(subset=['id'], keep=False)]
pd.set_option("display.max_rows",80)
dups[["id","name","artists","group"]].sort_values("id")

,id,name,artists,group
1137,0JJP0IS4w0fJx01EcrfkDe,"Dear Maria, Count Me In",All Time Low,comercial
185,0JJP0IS4w0fJx01EcrfkDe,"Dear Maria, Count Me In",All Time Low,alternative
1074,0TFTAtCYhp2tQ9KcJIZb55,undressed,sombr,comercial
600,0TFTAtCYhp2tQ9KcJIZb55,undressed,sombr,alternative
583,0eAuGrXyGFYwur9ARUe7LJ,Earrings,Malcolm Todd,alternative
1001,0eAuGrXyGFYwur9ARUe7LJ,Earrings,Malcolm Todd,comercial
7,0ofHAoxe9vBkTCp2UQIavz,Dreams - 2004 Remaster,Fleetwood Mac,alternative
1008,0ofHAoxe9vBkTCp2UQIavz,Dreams - 2004 Remaster,Fleetwood Mac,comercial
84,0q21FNwES2bbtcduB6kjEU,Dancing in the Moonlight,King Harvest,alternative
1162,0q21FNwES2bbtcduB6kjEU,Dancing in the Moonlight,King Harvest,comercial
1085,0qRR9d89hIS0MHRkQ0ejxX,Rich Girl,Daryl Hall & John Oates,comercial
31,0qRR9d89hIS0MHRkQ0ejxX,Rich Girl,Daryl Hall & John Oates,alternative
1070,1Bv3h7Vc4AaYA2BcSM3rVd,All I Wanted,Paramore,comercial
172,1Bv3h7Vc4AaYA2BcSM3rVd,All I Wanted,Paramore,alternative
50,1Cwsd5xI8CajJz795oy4XF,You Get What You Give,New Radicals,alternative
1109,1Cwsd5xI8CajJz795oy4XF,You Get What You Give,New Radicals,comercial
1356,1FvDJ9KGxcqwv1utyPL3JZ,This Charming Man - 2011 Remaster,The Smiths,comercial
688,1FvDJ9KGxcqwv1utyPL3JZ,This Charming Man - 2011 Remaster,The Smiths,alternative
592,1LzNfuep1bnAUR9skqdHCK,Fade Into You,Mazzy Star,alternative
1030,1LzNfuep1bnAUR9skqdHCK,Fade Into You,Mazzy Star,comercial
531,1aGzcNg5L2ej4ZKcz6GhKF,Shots - Instrumental,Illa J,alternative
1742,1aGzcNg5L2ej4ZKcz6GhKF,Shots - Instrumental,Illa J,comercial
1046,1oAwsWBovWRIp7qLMGPIet,Apocalypse,Cigarettes After Sex,comercial
591,1oAwsWBovWRIp7qLMGPIet,Apocalypse,Cigarettes After Sex,alternative
177,1yjY7rpaAQvKwpdUliHx0d,Still into You,Paramore,alternative
1071,1yjY7rpaAQvKwpdUliHx0d,Still into You,Paramore,comercial
1055,2374M0fQpWi3dLnB54qaLX,Africa,TOTO,comercial
18,2374M0fQpWi3dLnB54qaLX,Africa,TOTO,alternative
1075,254bXAqt3zP6P50BdQvEsq,Everywhere - 2017 Remaster,Fleetwood Mac,comercial
34,254bXAqt3zP6P50BdQvEsq,Everywhere - 2017 Remaster,Fleetwood Mac,alternative
1063,25FTMokYEbEWHEdss5JLZS,Teenage Dirtbag,Wheatus,comercial
27,25FTMokYEbEWHEdss5JLZS,Teenage Dirtbag,Wheatus,alternative
63,2BY7ALEWdloFHgQZG6VMLA,Brandy (You're a Fine Girl),Looking Glass,alternative
1124,2BY7ALEWdloFHgQZG6VMLA,Brandy (You're a Fine Girl),Looking Glass,comercial
1158,2XUx8PCXGpP1XhZJMGiUol,Chest Pain (I Love),Malcolm Todd,comercial
619,2XUx8PCXGpP1XhZJMGiUol,Chest Pain (I Love),Malcolm Todd,alternative
25,2hKdd3qO7cWr2Jo0Bcs0MA,Drops of Jupiter (Tell Me),Train,alternative
1050,2hKdd3qO7cWr2Jo0Bcs0MA,Drops of Jupiter (Tell Me),Train,comercial
1065,2m1hi0nfMR9vdGC8UcrnwU,All The Small Things,blink-182,comercial
174,2m1hi0nfMR9vdGC8UcrnwU,All The Small Things,blink-182,alternative
1035,33iv3wnGMrrDugd7GBso1z,My Own Worst Enemy,Lit,comercial
173,33iv3wnGMrrDugd7GBso1z,My Own Worst Enemy,Lit,alternative
1002,3qhlB30KknSejmIvZZLjOD,End of Beginning,Djo,comercial
584,3qhlB30KknSejmIvZZLjOD,End of Beginning,Djo,alternative
587,3siwsiaEoU4Kuuc9WKMUy5,No One Noticed,The Marías,alternative
1020,3siwsiaEoU4Kuuc9WKMUy5,No One Noticed,The Marías,comercial
607,41P6Tnd8KIHqON0QIydx6a,the perfect pair,beabadoobee,alternative
1122,41P6Tnd8KIHqON0QIydx6a,the perfect pair,beabadoobee,comercial
52,4IU1RL4BKvFyXtbTwaHAvW,Ventura Highway,"America, George Martin",alternative
1101,4IU1RL4BKvFyXtbTwaHAvW,Ventura Highway,"America, George Martin",comercial
1102,4RvWPyQ5RL0ao9LPZeSouE,Everybody Wants To Rule The World,Tears For Fears,comercial
46,4RvWPyQ5RL0ao9LPZeSouE,Everybody Wants To Rule The World,Tears For Fears,alternative
703,4o0LyB69tylqDG6eTGhmig,Fire for You,Cannons,alternative
1365,4o0LyB69tylqDG6eTGhmig,Fire for You,Cannons,comercial
1123,4o6BgsqLIBViaGVbx5rbRk,You Make My Dreams (Come True),Daryl Hall & John Oates,comercial
56,4o6BgsqLIBViaGVbx5rbRk,You Make My Dreams (Come True),Daryl Hall & John Oates,alternative
1076,4yugZvBYaoREkJKtbG08Qr,Take It Easy - 2013 Remaster,Eagles,comercial
35,4yugZvBYaoREkJKtbG08Qr,Take It Easy - 2013 Remaster,Eagles,alternative
9,5Ctzx0mMiUPAu9JqbAOY9n,Be Like a Woman,Chris Rainbow,alternative
1039,5Ctzx0mMiUPAu9JqbAOY9n,Be Like a Woman,Chris Rainbow,comercial
1005,5IMpnpD0tQVcqWlVIgtAtV,iloveitiloveitiloveit,Bella Kay,comercial
586,5IMpnpD0tQVcqWlVIgtAtV,iloveitiloveitiloveit,Bella Kay,alternative
1060,5ZdzNVOmCSp5HFLk0EgvJS,Dirty Little Secret,The All-American Rejects,comercial
171,5ZdzNVOmCSp5HFLk0EgvJS,Dirty Little Secret,The All-American Rejects,alternative
74,5fVZC9GiM4e8vu99W0Xf6J,How to Save a Life,The Fray,alternative
1148,5fVZC9GiM4e8vu99W0Xf6J,How to Save a Life,The Fray,comercial
1023,5ihS6UUlyQAfmp48eSkxuQ,Landslide,Fleetwood Mac,comercial
5,5ihS6UUlyQAfmp48eSkxuQ,Landslide,Fleetwood Mac,alternative
1058,6GG73Jik4jUlQCkKg9JuGO,The Middle,Jimmy Eat World,comercial
178,6GG73Jik4jUlQCkKg9JuGO,The Middle,Jimmy Eat World,alternative
1141,6IPwKM3fUUzlElbvKw2sKl,we fell in love in october,girl in red,comercial
612,6IPwKM3fUUzlElbvKw2sKl,we fell in love in october,girl in red,alternative
1004,6Qyc6fS4DsZjB2mRW9DsQs,Iris,The Goo Goo Dolls,comercial
2,6Qyc6fS4DsZjB2mRW9DsQs,Iris,The Goo Goo Dolls,alternative
53,7Ar4G7Ci11gpt6sfH9Cgz5,Listen to the Music,The Doobie Brothers,alternative
1092,7Ar4G7Ci11gpt6sfH9Cgz5,Listen to the Music,The Doobie Brothers,comercial
1136,7j31rVgGX9Q2blT92VBEA0,Teenagers,My Chemical Romance,comercial
182,7j31rVgGX9Q2blT92VBEA0,Teenagers,My Chemical Romance,alternative
54,7j74lucZ59vqN67Ipe2ZcY,Maneater,Daryl Hall & John Oates,alternative
1118,7j74lucZ59vqN67Ipe2ZcY,Maneater,Daryl Hall & John Oates,comercial

In [72]:
dups_name = df_merge[df_merge.duplicated(subset=['name'], keep=False)]
pd.set_option("display.max_rows",200)
dups_name[["id","name","artists","group"]].sort_values("name")

,id,name,artists,group
1154,2FQrifJ1N335Ljm3TjTVVf,A Bar Song (Tipsy),Shaboozey,comercial
1107,5fZJQrFKWQLb7FpJXZ1g7K,A Bar Song (Tipsy),Shaboozey,comercial
1460,5ZLUm9eab8y3tqQ1OhQSHI,Abracadabra,Lady Gaga,comercial
1366,2LHNTC9QZxsL3nWpt8iaSR,Abracadabra,Lady Gaga,comercial
18,2374M0fQpWi3dLnB54qaLX,Africa,TOTO,alternative
1055,2374M0fQpWi3dLnB54qaLX,Africa,TOTO,comercial
180,1j8z4TTjJ1YOdoFEDwJTQa,Ain't It Fun,Paramore,alternative
283,3yrvQHw6pQemsrCQEpMnKv,Ain't It Fun,Paramore,alternative
172,1Bv3h7Vc4AaYA2BcSM3rVd,All I Wanted,Paramore,alternative
1070,1Bv3h7Vc4AaYA2BcSM3rVd,All I Wanted,Paramore,comercial
1065,2m1hi0nfMR9vdGC8UcrnwU,All The Small Things,blink-182,comercial
174,2m1hi0nfMR9vdGC8UcrnwU,All The Small Things,blink-182,alternative
1046,1oAwsWBovWRIp7qLMGPIet,Apocalypse,Cigarettes After Sex,comercial
591,1oAwsWBovWRIp7qLMGPIet,Apocalypse,Cigarettes After Sex,alternative
9,5Ctzx0mMiUPAu9JqbAOY9n,Be Like a Woman,Chris Rainbow,alternative
1039,5Ctzx0mMiUPAu9JqbAOY9n,Be Like a Woman,Chris Rainbow,comercial
1086,190jyVPHYjAqEaOGmMzdyk,Beauty And A Beat,"Justin Bieber, Nicki Minaj",comercial
1015,6QFCMUUq1T2Vf5sFUXcuQ7,Beauty And A Beat,"Justin Bieber, Nicki Minaj",comercial
122,2EoOZnxNgtmZaD8uUmz2nD,Black Hole Sun,Soundgarden,alternative
132,4xdHI4eFNst0vTZuuKrWjr,Black Hole Sun,Soundgarden,alternative
63,2BY7ALEWdloFHgQZG6VMLA,Brandy (You're a Fine Girl),Looking Glass,alternative
1124,2BY7ALEWdloFHgQZG6VMLA,Brandy (You're a Fine Girl),Looking Glass,comercial
1158,2XUx8PCXGpP1XhZJMGiUol,Chest Pain (I Love),Malcolm Todd,comercial
619,2XUx8PCXGpP1XhZJMGiUol,Chest Pain (I Love),Malcolm Todd,alternative
1534,4jWH0iiS8CwGX2sQ9q2UTl,Circles,"Phatg, Tayo Xander",comercial
245,6zUy2nnchfZpzaDalE6sO2,Circles,Pierce The Veil,alternative
565,1Q2pRgyra39ffcdcHh2s59,Cowboys Don't Cry,Oliver Tree,alternative
1758,19wd0GBrwBl3HpPiMz1SMb,Cowboys Don't Cry,Oliver Tree,comercial
782,6mSjN3PUKVSFU26UkNcIp7,Cumbersome,Seven Mary Three,alternative
804,4p4WsKA5GjZ01jvNvvsu9m,Cumbersome,Seven Mary Three,alternative
1162,0q21FNwES2bbtcduB6kjEU,Dancing in the Moonlight,King Harvest,comercial
84,0q21FNwES2bbtcduB6kjEU,Dancing in the Moonlight,King Harvest,alternative
185,0JJP0IS4w0fJx01EcrfkDe,"Dear Maria, Count Me In",All Time Low,alternative
1137,0JJP0IS4w0fJx01EcrfkDe,"Dear Maria, Count Me In",All Time Low,comercial
171,5ZdzNVOmCSp5HFLk0EgvJS,Dirty Little Secret,The All-American Rejects,alternative
1060,5ZdzNVOmCSp5HFLk0EgvJS,Dirty Little Secret,The All-American Rejects,comercial
281,6LhGzSZlIGxZpyIXXZn9ZV,Dive In,Pierce The Veil,alternative
993,0xtSjpkLpHpRbeH9gGYKuv,Dive In,Glassmanet,alternative
7,0ofHAoxe9vBkTCp2UQIavz,Dreams - 2004 Remaster,Fleetwood Mac,alternative
1008,0ofHAoxe9vBkTCp2UQIavz,Dreams - 2004 Remaster,Fleetwood Mac,comercial
25,2hKdd3qO7cWr2Jo0Bcs0MA,Drops of Jupiter (Tell Me),Train,alternative
1050,2hKdd3qO7cWr2Jo0Bcs0MA,Drops of Jupiter (Tell Me),Train,comercial
1001,0eAuGrXyGFYwur9ARUe7LJ,Earrings,Malcolm Todd,comercial
583,0eAuGrXyGFYwur9ARUe7LJ,Earrings,Malcolm Todd,alternative
584,3qhlB30KknSejmIvZZLjOD,End of Beginning,Djo,alternative
1002,3qhlB30KknSejmIvZZLjOD,End of Beginning,Djo,comercial
46,4RvWPyQ5RL0ao9LPZeSouE,Everybody Wants To Rule The World,Tears For Fears,alternative
1102,4RvWPyQ5RL0ao9LPZeSouE,Everybody Wants To Rule The World,Tears For Fears,comercial
115,2YiCMmONQcoMPX2bV1LxE0,Everybody Wants To Rule The World,Tears For Fears,alternative
34,254bXAqt3zP6P50BdQvEsq,Everywhere - 2017 Remaster,Fleetwood Mac,alternative
1075,254bXAqt3zP6P50BdQvEsq,Everywhere - 2017 Remaster,Fleetwood Mac,comercial
1030,1LzNfuep1bnAUR9skqdHCK,Fade Into You,Mazzy Star,comercial
592,1LzNfuep1bnAUR9skqdHCK,Fade Into You,Mazzy Star,alternative
1365,4o0LyB69tylqDG6eTGhmig,Fire for You,Cannons,comercial
703,4o0LyB69tylqDG6eTGhmig,Fire for You,Cannons,alternative
807,7JSzWjZdyc5myqoCNZoI8Y,Good,Better Than Ezra,alternative
781,4Tx7CO2iXPTI5Kp7fiK2XZ,Good,Better Than Ezra,alternative
819,4iOImWWanc5QoG51V4za9f,Hold My Hand - Don Gehman Remix,Hootie & The Blowfish,alternative
801,3vUQMUnNpNsADQoUN2O5G9,Hold My Hand - Don Gehman Remix,Hootie & The Blowfish,alternative
786,0Zft36o2sWS4XMm9t8gbF6,Hold My Hand - Don Gehman Remix,Hootie & The Blowfish,alternative
784,77MZp8srPY25bgOD3aH0VA,Hold My Hand - Don Gehman Remix,Hootie & The Blowfish,alternative
789,1MaEVcQaP2cwnnFg1x3QAS,How You Remind Me,Nickelback,alternative
803,3Vvbw8qFHNnGtA7WBcyBTX,How You Remind Me,Nickelback,alternative
810,72RDBNxPbzsdcaPPIibjKl,How You Remind Me,Nickelback,alternative
74,5fVZC9GiM4e8vu99W0Xf6J,How to Save a Life,The Fray,alternative
1148,5fVZC9GiM4e8vu99W0Xf6J,How to Save a Life,The Fray,comercial
894,0Yj6JVmXkg7e6jXGzmh0E9,I Fought the Law,The Bobby Fuller Four,alternative
867,4zj9ul9Tn3P1JNdKz0iybZ,I Fought the Law,The Bobby Fuller Four,alternative
1016,6f68Ac5tt5BQOpwr0BV9oN,I Just Might,Bruno Mars,comercial
1089,12bYYQaLqHliSXvRIYlq8G,I Just Might,Bruno Mars,comercial
864,0go5vJnJS3k7hGAcwFxaDn,"I Need Your Loving - Live at Funny Park, Denma...",The Artwoods,alternative
826,0qcVTV2dGsm8WWAhuKkAjp,"I Need Your Loving - Live at Funny Park, Denma...",The Artwoods,alternative
730,7Fv6spqqdLcWZVxtMBtQDJ,I Want Cunt,The Queers,alternative
765,2V543H8JOzRPKDfjK22eMm,I Want Cunt,The Queers,alternative
719,0iDxFFd9vJCuDU0ptpYPkP,I Want to Know What Love Is - 1999 Remaster,Foreigner,alternative
748,3JWkBQDJHRNizOmnooW1Qp,I Want to Know What Love Is - 1999 Remaster,Foreigner,alternative
758,7fUCBoLlar49SNjTlt6lah,I Want to Know What Love Is - 1999 Remaster,Foreigner,alternative
772,4hnu6VPK6W0jcXUTk7Q8xY,I Want to Know What Love Is - 1999 Remaster,Foreigner,alternative
878,0bnDfoC4UzZL3r3JiKTdBa,Imposters of Life's Magazine,The Idle Race,alternative
827,676lg6mLU4ybdszhnHHcJy,Imposters of Life's Magazine,The Idle Race,alternative
817,0At5TiGc8ZPxay70lanN2J,In the Meantime,Spacehog,alternative
797,4pm4UUFktCFT2FRTCMaNBV,In the Meantime,Spacehog,alternative
1749,75EkrfyTTasjZjKdsXCDMO,Intro,"Saigon, Fredro",comercial
1713,5jpPgLJpT9dTysQ3lMrTgb,Intro,Tykoon Suit,comercial
718,072Hr4MHnhA0CWP63fWzy3,Intro,Black Drawing Chalks,alternative
1769,64UERTRP5EpeywgMutgHJb,Intro,"Ison & Fille, ISON, Fille Danza",comercial
892,2Co77wAL8ZIR3r50DP3Csx,Intro,Inner Wave,alternative
962,5OJqIiHmBp8lpVelE2GKIv,Intro,Gaadge,alternative
1311,5bIrrkreqXEnpB6AzSRdVj,Intro,Habacuc Threeseven,comercial
1004,6Qyc6fS4DsZjB2mRW9DsQs,Iris,The Goo Goo Dolls,comercial
2,6Qyc6fS4DsZjB2mRW9DsQs,Iris,The Goo Goo Dolls,alternative
802,1VrDcHfA1Bm5ZuYSUvHxMB,Iris - Acoustic,The Goo Goo Dolls,alternative
808,4ds0jDOHIX3QeK3zFmTLlv,Iris - Acoustic,The Goo Goo Dolls,alternative
613,1jJci4qxiYcOHhQR247rEU,Kids,MGMT,alternative
690,6cMMZ2pdP4PkYsVJqX2WUh,Kids,Current Joys,alternative
1219,4oowI6IgJp9oqUnJewTp6Y,LINDA,"Tito Double P, Neton Vega",comercial
1223,7qXptgpZGo8AFPhJCBVLFE,LINDA,"Tito Double P, Neton Vega",comercial
1023,5ihS6UUlyQAfmp48eSkxuQ,Landslide,Fleetwood Mac,comercial
5,5ihS6UUlyQAfmp48eSkxuQ,Landslide,Fleetwood Mac,alternative
1092,7Ar4G7Ci11gpt6sfH9Cgz5,Listen to the Music,The Doobie Brothers,comercial
53,7Ar4G7Ci11gpt6sfH9Cgz5,Listen to the Music,The Doobie Brothers,alternative
364,37ZJ0p5Jm13JPevGcx4SkF,Livin' On A Prayer,Bon Jovi,alternative
159,0ee1DiZF94NSqqpG0XHUzH,Livin' On A Prayer,Bon Jovi,alternative
883,5K87k0RdEKAqQSXQe9NRIu,Love Have Mercy / Bony Moronie / Love Have Mer...,The Artwoods,alternative
876,4Ds1RKQxoCRYClVkQzTv6X,Love Have Mercy / Bony Moronie / Love Have Mer...,The Artwoods,alternative
54,7j74lucZ59vqN67Ipe2ZcY,Maneater,Daryl Hall & John Oates,alternative
1118,7j74lucZ59vqN67Ipe2ZcY,Maneater,Daryl Hall & John Oates,comercial
1106,1qRV1dKLOfH1s00b9J2LUQ,Midnight Sun,Zara Larsson,comercial
1316,37UCSVSqiPGdR1DijOFyYY,Midnight Sun,Zara Larsson,comercial
790,5OZnwHHfzzDFDRHXwwRRZB,My Hometown,Uncle Kracker,alternative
793,10yeyQng9u0zuIOgikVubj,My Hometown,Uncle Kracker,alternative
173,33iv3wnGMrrDugd7GBso1z,My Own Worst Enemy,Lit,alternative
1035,33iv3wnGMrrDugd7GBso1z,My Own Worst Enemy,Lit,comercial
838,41gN0yydehbtNOuLg130rN,My Special Angel,The Vogues,alternative
824,3PTzjJYWwQPT6nYwmrWeg5,My Special Angel,The Vogues,alternative
587,3siwsiaEoU4Kuuc9WKMUy5,No One Noticed,The Marías,alternative
1020,3siwsiaEoU4Kuuc9WKMUy5,No One Noticed,The Marías,comercial
787,1QxUBbiUuISEjQXfmpofp2,Not Even the Trees,Hootie & The Blowfish,alternative
791,0QI5bKX9SoUxm94m4yagzR,Not Even the Trees,Hootie & The Blowfish,alternative
419,4myFsmx2v6znDOJfn3IkbD,Popular Monster,Falling In Reverse,alternative
467,4GssB27iJeqmfGxS94Tfij,Popular Monster,Falling In Reverse,alternative
1267,5jHozZMWbrExAFni95mvvH,Por Esos Ojos,Fuerza Regida,comercial
1190,77pDO4WZPIdkwFve0iHWnb,Por Esos Ojos,Fuerza Regida,comercial
1206,6x59lSlNU7TvsJZy7134uC,ROSONES,"Jorsshh, Fuerza Regida",comercial
1199,0LTwdL5yZ6YOTEGUQPFuSN,ROSONES,Tito Double P,comercial
928,7IjCArZjX7GfOYMMpZZKGM,Race,broaddaylight,alternative
1519,5LPosFK0bPzzfWEu1Uq5gb,Race,Dmajormusic,comercial
31,0qRR9d89hIS0MHRkQ0ejxX,Rich Girl,Daryl Hall & John Oates,alternative
1085,0qRR9d89hIS0MHRkQ0ejxX,Rich Girl,Daryl Hall & John Oates,comercial
596,2uXlHCUbq9OMUwx3hrk06o,Riptide,Vance Joy,alternative
707,7yq4Qj7cqayVTp3FF9CWbm,Riptide,Vance Joy,alternative
717,2urcc1FGpTvZrqSJMvNnAl,Ruas (Ao Vivo),Pastel de Miolos,alternative
757,4vsFbIvBhXPaCP1NrdnrRx,Ruas (Ao Vivo),Pastel de Miolos,alternative
412,0X1sqQ652p1sceKM2nJlIJ,Runaway,Bon Jovi,alternative
397,6xtQ23d8GEXgcxyUKPtwc5,Runaway,Linkin Park,alternative
1252,1UMm1Qs3u59Wvk53zBUE8r,SABOR FRESA,Fuerza Regida,comercial
1251,3kx21xR6IboC9HVdajgBoc,SABOR FRESA,Fuerza Regida,comercial
875,77xDZXibL4eU80XaCoIozJ,"Shake - Live at Funny Park, Denmark, 1967",The Artwoods,alternative
887,4gPHS6WkF254zFv1SNdZBH,"Shake - Live at Funny Park, Denmark, 1967",The Artwoods,alternative
1742,1aGzcNg5L2ej4ZKcz6GhKF,Shots - Instrumental,Illa J,comercial
531,1aGzcNg5L2ej4ZKcz6GhKF,Shots - Instrumental,Illa J,alternative
1454,5ITV0zqzjOYfFWpW0xBmRa,Show Me Love,"WizTheMc, bees & honey",comercial
1394,4t0UsYzmmmZRMTWn77jiGF,Show Me Love,Robin S,comercial
1235,0n2SEXB2qoRQg171q7XqeW,Smooth (feat. Rob Thomas),"Santana, Rob Thomas",comercial
1195,2pX4FpOgwItRVPPUFdRcxA,Smooth (feat. Rob Thomas),"Santana, Rob Thomas",comercial
880,0SWaIK0ILUBe28q6i9h1MJ,"Song of the Journeyman - Live at Funny Park, D...",The Artwoods,alternative
837,1sEEO257VmsyYUHauydfxM,"Song of the Journeyman - Live at Funny Park, D...",The Artwoods,alternative
901,39UHA7aX1Y4P8ywMWLKrHc,Spooky,Classics IV,alternative
858,0uJ4aMOpkXN7dP3zqC0KYs,Spooky,Classics IV,alternative
1416,74y1VgzL668hynrvA59WQB,Stay,FISHER,comercial
1363,6uBhi9gBXWjanegOb2Phh0,Stay,"Zedd, Alessia Cara",comercial
284,3SXXFIZel1VQQ4ENiqozxi,Still into You,Paramore,alternative
1071,1yjY7rpaAQvKwpdUliHx0d,Still into You,Paramore,comercial
177,1yjY7rpaAQvKwpdUliHx0d,Still into You,Paramore,alternative
763,5yYnhgjDjfk96gW3RWZO5o,Stone Cold Love,The Treatment,alternative
732,7zxzHuUVzEE92Fasim7HZd,Stone Cold Love,The Treatment,alternative
902,4e7DuzG34ob8hjdfYFbd9S,Summertime,The Buckinghams,alternative
828,3JuxbLg068tcCHzpEPEC9H,Summertime,Vanity Fare,alternative
1076,4yugZvBYaoREkJKtbG08Qr,Take It Easy - 2013 Remaster,Eagles,comercial
35,4yugZvBYaoREkJKtbG08Qr,Take It Easy - 2013 Remaster,Eagles,alternative
1063,25FTMokYEbEWHEdss5JLZS,Teenage Dirtbag,Wheatus,comercial
27,25FTMokYEbEWHEdss5JLZS,Teenage Dirtbag,Wheatus,alternative
182,7j31rVgGX9Q2blT92VBEA0,Teenagers,My Chemical Romance,alternative
1136,7j31rVgGX9Q2blT92VBEA0,Teenagers,My Chemical Romance,comercial
1438,7rl7ao5pb9BhvAzPdWStxi,Telephone,"Lady Gaga, Beyoncé",comercial
1332,4TCL0qqKyqsMZml0G3M9IM,Telephone,"Lady Gaga, Beyoncé",comercial
1058,6GG73Jik4jUlQCkKg9JuGO,The Middle,Jimmy Eat World,comercial
178,6GG73Jik4jUlQCkKg9JuGO,The Middle,Jimmy Eat World,alternative
688,1FvDJ9KGxcqwv1utyPL3JZ,This Charming Man - 2011 Remaster,The Smiths,alternative
1356,1FvDJ9KGxcqwv1utyPL3JZ,This Charming Man - 2011 Remaster,The Smiths,comercial
52,4IU1RL4BKvFyXtbTwaHAvW,Ventura Highway,"America, George Martin",alternative
1101,4IU1RL4BKvFyXtbTwaHAvW,Ventura Highway,"America, George Martin",comercial
1054,7eYzn1CuiJK6VvUhf8zA6k,WHERE IS MY HUSBAND!,RAYE,comercial
1068,55lijDD6OAjLFFUHU9tcDm,WHERE IS MY HUSBAND!,RAYE,comercial
452,0oerlffJSzhRVvtDfLcp3N,Wanted Dead Or Alive,Bon Jovi,alternative
458,52m7IQitPjIy1PrULHhS9F,Wanted Dead Or Alive,Bon Jovi,alternative
874,2GvvVqqAsej6SFdQuqzU5S,Wolfman,The Bobby Fuller Four,alternative
891,7l83GiLMzxM1MKPYgeEGVC,Wolfman,The Bobby Fuller Four,alternative
844,0XmRh1WqNGNnSZ4KZE00yj,Wolfman,The Bobby Fuller Four,alternative
1680,1pOlwUz42daurq7qXoovD4,Worldwide,Ruffcoin,comercial
1496,1nHvQR9X4i7bQi8mv8N3yv,Worldwide,"Tatchy, Classe Beats",comercial
1109,1Cwsd5xI8CajJz795oy4XF,You Get What You Give,New Radicals,comercial
50,1Cwsd5xI8CajJz795oy4XF,You Get What You Give,New Radicals,alternative
371,2TofEeQobQ9YoK7EFds698,You Give Love A Bad Name,Bon Jovi,alternative
402,0rmGAIH9LNJewFw7nKzZnc,You Give Love A Bad Name,Bon Jovi,alternative
1123,4o6BgsqLIBViaGVbx5rbRk,You Make My Dreams (Come True),Daryl Hall & John Oates,comercial
56,4o6BgsqLIBViaGVbx5rbRk,You Make My Dreams (Come True),Daryl Hall & John Oates,alternative
1213,4icM6ny646bWf318ws9LWz,chiclona,"Peso Pluma, Tito Double P, LENCHO",comercial
1173,5Q4HTsEGKanxOwL1nYCnhQ,chiclona,"Peso Pluma, Tito Double P, LENCHO",comercial
586,5IMpnpD0tQVcqWlVIgtAtV,iloveitiloveitiloveit,Bella Kay,alternative
1005,5IMpnpD0tQVcqWlVIgtAtV,iloveitiloveitiloveit,Bella Kay,comercial
1122,41P6Tnd8KIHqON0QIydx6a,the perfect pair,beabadoobee,comercial
607,41P6Tnd8KIHqON0QIydx6a,the perfect pair,beabadoobee,alternative
600,0TFTAtCYhp2tQ9KcJIZb55,undressed,sombr,alternative
1074,0TFTAtCYhp2tQ9KcJIZb55,undressed,sombr,comercial
1141,6IPwKM3fUUzlElbvKw2sKl,we fell in love in october,girl in red,comercial
612,6IPwKM3fUUzlElbvKw2sKl,we fell in love in october,girl in red,alternative
1583,70YBYXM5stQIvFz3OhqWDV,Как дела,Айкын,comercial
1601,5nBp19JR0gaeQWOgahWuno,Как дела,Айкын,comercial

In [103]:
def clean_data(df):
    df = df.sort_values("group",ascending=True)
    df= df.drop_duplicates(subset=['id'],keep="first")
    df= df.drop_duplicates(subset=["name","artists"],keep="first")
    df["release_date"] = pd.to_datetime(df["release_date"],format="mixed")
    df["release_year"] = df["release_date"].dt.year
    df = df.drop(columns=["release_date"])
    df=df.reset_index(drop=True)
    return df

In [104]:
data = clean_data(df_merge)
dup = data[data.duplicated(subset=["id"], keep=False)]
pd.set_option("display.max_rows",80)
dup[["id","name","artists","group"]].sort_values("id")

Empty DataFrame
Columns: [id, name, artists, group]
Index: []

In [105]:
dups2 = data[data.duplicated(subset=['name'], keep=False)]
pd.set_option("display.max_rows",200)
dups2[["id","name","artists","group"]].sort_values("name")

,id,name,artists,group
966,4jWH0iiS8CwGX2sQ9q2UTl,Circles,"Phatg, Tayo Xander",comercial
561,6zUy2nnchfZpzaDalE6sO2,Circles,Pierce The Veil,alternative
331,0xtSjpkLpHpRbeH9gGYKuv,Dive In,Glassmanet,alternative
871,6LhGzSZlIGxZpyIXXZn9ZV,Dive In,Pierce The Veil,alternative
1548,5bIrrkreqXEnpB6AzSRdVj,Intro,Habacuc Threeseven,comercial
1242,75EkrfyTTasjZjKdsXCDMO,Intro,"Saigon, Fredro",comercial
1214,64UERTRP5EpeywgMutgHJb,Intro,"Ison & Fille, ISON, Fille Danza",comercial
1181,5jpPgLJpT9dTysQ3lMrTgb,Intro,Tykoon Suit,comercial
92,072Hr4MHnhA0CWP63fWzy3,Intro,Black Drawing Chalks,alternative
363,5OJqIiHmBp8lpVelE2GKIv,Intro,Gaadge,alternative
472,2Co77wAL8ZIR3r50DP3Csx,Intro,Inner Wave,alternative
95,6cMMZ2pdP4PkYsVJqX2WUh,Kids,Current Joys,alternative
203,1jJci4qxiYcOHhQR247rEU,Kids,MGMT,alternative
1635,6x59lSlNU7TvsJZy7134uC,ROSONES,"Jorsshh, Fuerza Regida",comercial
1628,0LTwdL5yZ6YOTEGUQPFuSN,ROSONES,Tito Double P,comercial
967,5LPosFK0bPzzfWEu1Uq5gb,Race,Dmajormusic,comercial
267,7IjCArZjX7GfOYMMpZZKGM,Race,broaddaylight,alternative
726,0X1sqQ652p1sceKM2nJlIJ,Runaway,Bon Jovi,alternative
773,6xtQ23d8GEXgcxyUKPtwc5,Runaway,Linkin Park,alternative
1085,4t0UsYzmmmZRMTWn77jiGF,Show Me Love,Robin S,comercial
1146,5ITV0zqzjOYfFWpW0xBmRa,Show Me Love,"WizTheMc, bees & honey",comercial
1082,74y1VgzL668hynrvA59WQB,Stay,FISHER,comercial
1597,6uBhi9gBXWjanegOb2Phh0,Stay,"Zedd, Alessia Cara",comercial
303,4e7DuzG34ob8hjdfYFbd9S,Summertime,The Buckinghams,alternative
458,3JuxbLg068tcCHzpEPEC9H,Summertime,Vanity Fare,alternative
1320,1pOlwUz42daurq7qXoovD4,Worldwide,Ruffcoin,comercial
989,1nHvQR9X4i7bQi8mv8N3yv,Worldwide,"Tatchy, Classe Beats",comercial

In [107]:
pd.set_option("display.max_rows", 10)
data.sort_values("name")

,id,name,artists,acousticness,danceability,energy,valence,group,release_year
512,5QTxFnGygVM4jFQiBovmRo,(Don't Fear) The Reaper,Blue Öyster Cult,0.002900,0.333,0.927,0.385,alternative,1976
318,3IdGsNPa6iolbZVY1v3VWg,(doze off),Her Stems Spiral,0.027500,0.255,0.288,0.463,alternative,2022
1171,3kAC9PtMOWBusalSsJ4Uqi,(אינטרלוד) - אומנות,Sagi Braitner,0.916000,0.732,0.633,0.455,comercial,2021
868,427OHPoIWqO3SsFw77EkDf,*Equip Sunglasses*,Hot Mulligan,0.000747,0.628,0.967,0.906,alternative,2020
954,794wvyVcaQpECvWCBQpaTB,*Sobs Quietly*,Mom Jeans.,0.005990,0.422,0.785,0.396,alternative,2016
...,...,...,...,...,...,...,...,...,...
328,2FENXNvcFlbh5Tre0anISj,넌 새로워 - Instrumental,Lee Seol Ah,0.442000,0.734,0.243,0.113,alternative,2017
1295,4YKEKe5pRhR8QHYZOFuOdm,세노야 세노야,Yang Hee Eun,0.954000,0.399,0.032,0.202,comercial,1994
1198,09ibmyZztW0gqvb3DWnFhY,아버지와 아들,Honey Family,0.660000,0.592,0.083,0.841,comercial,2000
1021,15t8MqOGZq7iXVTXpKi5Dz,우린 너무 쉽게 헤어졌어요,Choi JinHee,0.610000,0.421,0.284,0.419,comercial,1994
1283,6St9jAqn3In3QaJW2IaGMB,찻집의 고독,KIM CHOO JA,0.284000,0.513,0.249,0.432,comercial,1994